### ISSUE TITLE
Adding joints hierarchy

### ISSUE THREAD

**Issue by ppiecuch** [JosephCatrambone/godot-bvh-import#2]
Hello, I have one small question: I have added an option to build a skeleton hierarchy from bvh definition - so far so good:

<img width="1237" alt="Screenshot 2020-10-04 at 13 23 52" src="https://user-images.githubusercontent.com/1011685/95018356-86e8de00-065f-11eb-9d73-9d2499938dae.png">

But when I try to play AnimationPlay, everything is collapsing:

<img width="1240" alt="Screenshot 2020-10-04 at 13 24 59" src="https://user-images.githubusercontent.com/1011685/95018361-8ea88280-065f-11eb-9890-fbf273154c07.png">

Could you shed some light on this? Could this be a problem with imported animations' transforms?

Regards
Pawel

**Comment by JosephCatrambone** [comment]
Hi there.  Sorry for the delay -- didn't notice this issue was created.  Any chance I can impose upon to you to share the BVH?

**Comment by ppiecuch** [comment]
Hi - I managed to sove this using IGNORE_OFSSETS option. Thanks.

**Comment by GeorgeS2019** [comment]
@ppiecuch @JosephCatrambone Could one of you include the ability to [build a skeleton hierarchy from bvh definition](https://gist.github.com/ppiecuch/c1034d40fc5c1f18367e4fab0c23f0fd)
